### ISSUE TITLE
SyntaxError: invalid syntax

### ISSUE THREAD

**Issue by aishoot** [chimechallenge/chime5-synchronisation#1]
File "estimate_alignment.py", line 65
    signal = struct.unpack(f'{nsamples * nchannels}h', wavbytes)
                                                    ^
SyntaxError: invalid syntax
  File "estimate_alignment.py", line 65
    signal = struct.unpack(f'{nsamples * nchannels}h', wavbytes)
                                                    ^
SyntaxError: invalid syntax
  File "align_transcription.py", line 82
    align_data = pickle.load(open(f'{align_data_path}/align.{session}.p', 'rb'))
                                                                       ^
SyntaxError: invalid syntax
  File "view_alignments.py", line 32
    name = f'{path}/align.{session}.p'
                                     ^
SyntaxError: invalid syntax

**Comment by jonbarker68** [comment]
A python version >=3.6 is required.

**Comment by aishoot** [comment]
@jonbarker68 OK, thanks.
